baseURL: http://wedesign-micro-blog.s3-website-eu-west-1.amazonaws.com//
languageCode: en-uk
title: micro.blog
theme: "PaperMod"
paginate: 10

enableRobotsTXT: false

minify:
  disableXML: false
  minifyOutput: false

params:
  env: production 
  description: "micro.blog | by weDesign.ie"
  keywords: [micro, blog, notes, thoughts, ideas, cyber, security, privacy, 
  technology, parenthood]
  author: Theodore
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2 January 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: false

  # editPost:
  #       URL: "https://github.com/theodorekall/"
  #       Text: "Suggest Changes" # edit text
  #       appendFilePath: true # to append file path to Edit link

  homeInfoParams:
    Title: "Hi there! \U0001F44B"
    Content: These are the ramblings of a dad, web developer & cyber security enthusiast.

  socialIcons:
    - name: github
      url: "https://github.com/theodorekall/"

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
    linkFullImages: true
    responsiveImages: false

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

assets:
#   # disableHLJS: true # to disable highlight.js
#   # disableFingerprinting: true
  favicon: "/img/icon.png"
  favicon16x16: "/img/icon.png"
  favicon32x32: "/img/icon.png"
  apple_touch_icon: "/img/icon.png"
  safari_pinned_tab: "/img/icon.png"

label:
  text: "Home"
  icon: /apple-touch-icon.png
  iconHeight: 35

# analytics:
#   google:
#     SiteVerificationTag: "XYZabc"
#   bing:
#     SiteVerificationTag: "XYZabc"
#   yandex:
#     SiteVerificationTag: "XYZabc"


menu:
  main:
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30

deployment:
  targets: 
    name: C:\Users\Theodore\Documents\micro.blog\build